#!/usr/bin/env python3
"""
build_seed_db.py
================
Writes seed_bibliography.csv — the verified starting core of the review database.

Every record below was retrieved live from OpenAlex/Semantic Scholar during the
Stage-1 search and carries a real DOI. Nothing is reconstructed from memory.
The coding columns are populated only where the abstract states the value
explicitly; everything else is left blank for the full-text pass, and 'unclear'
is a legitimate value that must survive into the audit.
"""

import csv
from pathlib import Path

COLUMNS = [
    "doi", "year", "authors", "title", "venue", "cited_by_count",
    "role_in_review", "pavement_domain", "pavement_family", "architecture",
    "optimizer_hybrid", "data_source", "n_samples", "interpretability_method",
    "deployment_evidence", "note",
]

R = [
    # --- prior reviews: the territory map (§1 of the architecture doc) ---
    dict(doi="10.1016/j.jtte.2021.03.005", year=2021,
         authors="Yang, X.; Guan, J.; Ding, L.; et al.",
         title="Research and applications of artificial neural network in pavement engineering: A state-of-the-art review",
         venue="J. Traffic Transp. Eng. (Engl. Ed.)", cited_by_count=111,
         role_in_review="prior review — closest competitor", pavement_domain="all",
         pavement_family="general", architecture="MLP/CNN/RNN (survey)",
         optimizer_hybrid="", data_source="literature", n_samples="683 retrieved / 143 reviewed",
         interpretability_method="", deployment_evidence="none",
         note="Defines the gap we must clear. Stops at MLP/CNN/RNN; no rigour audit; pre-dates the hybrid/XAI/transformer wave."),
    dict(doi="10.3390/data3030028", year=2018, authors="Gopalakrishnan, K.",
         title="Deep learning in data-driven pavement image analysis and automated distress detection: A review",
         venue="Data", cited_by_count=205, role_in_review="prior review",
         pavement_domain="distress-detection", pavement_family="general",
         architecture="CNN (survey)", optimizer_hybrid="", data_source="literature",
         n_samples="", interpretability_method="", deployment_evidence="none",
         note="Narrative review; owns the early DL-vision territory."),
    dict(doi="10.1109/access.2020.2966881", year=2020, authors="Cao, W.; Liu, Q.; He, Z.",
         title="Review of pavement defect detection methods",
         venue="IEEE Access", cited_by_count=303, role_in_review="prior review",
         pavement_domain="distress-detection", pavement_family="general",
         architecture="image-processing / ML / DL / 3D (survey)", optimizer_hybrid="",
         data_source="literature", n_samples="", interpretability_method="",
         deployment_evidence="none",
         note="Benchmark-and-metric comparison; useful source for our §7 comparability critique."),
    dict(doi="10.1016/j.eng.2020.07.030", year=2020, authors="Hou, Y.; Li, Q.; Zhang, C.; et al.",
         title="The state-of-the-art review on applications of intrusive sensing, image processing techniques, and machine learning methods in pavement monitoring and analysis",
         venue="Engineering", cited_by_count=278, role_in_review="prior review",
         pavement_domain="structural-evaluation/distress-detection", pavement_family="general",
         architecture="mixed (survey)", optimizer_hybrid="", data_source="literature",
         n_samples="", interpretability_method="", deployment_evidence="none", note=""),
    dict(doi="10.1016/j.conbuildmat.2022.126686", year=2022,
         authors="Rasol, M.; Pais, J. C.; Pérez-Gracia, V.; et al.",
         title="GPR monitoring for road transport infrastructure: A systematic review and machine learning insights",
         venue="Constr. Build. Mater.", cited_by_count=178, role_in_review="prior review",
         pavement_domain="structural-evaluation", pavement_family="general",
         architecture="ML (survey)", optimizer_hybrid="", data_source="literature",
         n_samples="", interpretability_method="", deployment_evidence="none", note=""),
    dict(doi="10.1016/j.jreng.2023.12.001", year=2023,
         authors="Cavalli, M. C.; Chen, D.; Chen, Q.; et al. (39 authors)",
         title="Review of advanced road materials, structures, equipment, and detection technologies",
         venue="J. Road Eng.", cited_by_count=79, role_in_review="prior review",
         pavement_domain="all", pavement_family="general", architecture="mixed (survey)",
         optimizer_hybrid="", data_source="literature", n_samples="",
         interpretability_method="", deployment_evidence="none",
         note="Omnibus; AI is one strand among many — leaves our niche open."),
    dict(doi="10.13167/2026.32.7", year=2026,
         authors="Zagvozda, M.; Ljutić, K.; Janić, V.; et al.",
         title="AI for pavement distress detection on lower-ranking roads: A bibliometric and systematic review",
         venue="Adv. Civ. Archit. Eng.", cited_by_count=0, role_in_review="prior review — very recent",
         pavement_domain="distress-detection", pavement_family="low-volume",
         architecture="YOLO/CNN (survey)", optimizer_hybrid="", data_source="literature",
         n_samples="98 studies", interpretability_method="", deployment_evidence="none",
         note="Confirms the ground-truthing and benchmark-standardisation gaps we intend to quantify."),
    dict(doi="10.1186/s43065-026-00178-y", year=2026,
         authors="Hariri Asli, H.; Brake, N.; Nikookar, M.; et al.",
         title="Application of artificial intelligence methods in the international roughness index prediction of rigid and composite pavements: a systematic review",
         venue="J. Infrastruct. Preserv. Resil.", cited_by_count=0,
         role_in_review="prior review — very recent", pavement_domain="performance-prediction",
         pavement_family="rigid/composite", architecture="ensemble/ANN/hybrid (survey)",
         optimizer_hybrid="", data_source="LTPP-dominated", n_samples="23 studies",
         interpretability_method="", deployment_evidence="none",
         note="Narrow slice of our §8; cite as evidence of LTPP dependency, do not overlap scope."),

    # --- Ghanizadeh corpus (verified) ---
    dict(doi="10.1007/s41062-020-00312-z", year=2020,
         authors="Ghanizadeh, A. R.; Heidarabadizadeh, N.; Jalali, F.",
         title="Artificial neural network back-calculation of flexible pavements with sensitivity analysis using Garson's and connection weights algorithms",
         venue="Innov. Infrastruct. Solut.", cited_by_count=43,
         role_in_review="primary — §5 & §10", pavement_domain="structural-evaluation",
         pavement_family="flexible", architecture="MLP", optimizer_hybrid="none",
         data_source="simulated-FEM/layered-elastic", n_samples="",
         interpretability_method="Garson; connection-weights", deployment_evidence="none",
         note="Anchor for the inverse-problem section and for pre-SHAP interpretability lineage."),
    dict(doi="10.1016/j.ijprt.2017.09.002", year=2017,
         authors="Ghanizadeh, A. R.; Fakhri, M.",
         title="Quasi-static analysis of flexible pavements based on predicted frequencies using Fast Fourier Transform and Artificial Neural Network",
         venue="Int. J. Pavement Res. Technol.", cited_by_count=14,
         role_in_review="primary — §6", pavement_domain="structural-response",
         pavement_family="flexible", architecture="feed-forward ANN", optimizer_hybrid="none",
         data_source="simulated (1200 sections) + Virginia Smart Road field check",
         n_samples="1200 sections", interpretability_method="none",
         deployment_evidence="equation/nomograph",
         note="Rare and valuable: synthetic training WITH an independent field comparison. Positive exemplar for §11."),
    dict(doi="10.1155/2014/515467", year=2014,
         authors="Ghanizadeh, A. R.; Fakhri, M.",
         title="Prediction of frequency for simulation of asphalt mix fatigue tests using MARS and ANN",
         venue="The Scientific World Journal", cited_by_count=17,
         role_in_review="primary — §6", pavement_domain="materials/test-simulation",
         pavement_family="flexible", architecture="ANN; MARS", optimizer_hybrid="none",
         data_source="simulated (5000 sections)", n_samples="5000",
         interpretability_method="MARS basis functions (intrinsic)", deployment_evidence="equation",
         note="Early example of pairing a black-box with an intrinsically interpretable model — theme of §10."),
    dict(doi="10.1038/s41598-024-61313-x", year=2024,
         authors="Ghanizadeh, A. R.; Tavana Amlashi, A.; Bahrami, A.; et al.",
         title="A formulation for asphalt concrete air void during service life by adopting a hybrid evolutionary polynomial regression and multi-gene genetic programming",
         venue="Scientific Reports", cited_by_count=8,
         role_in_review="primary — §4 & §10", pavement_domain="materials",
         pavement_family="flexible", architecture="EPR; MGGP", optimizer_hybrid="TLBO",
         data_source="literature-compiled", n_samples="324",
         interpretability_method="closed-form equation (intrinsic); sensitivity; parametric study",
         deployment_evidence="equation",
         note="Symbolic-regression counterpoint to opaque learners; supports the §10 argument."),
    dict(doi="10.3390/infrastructures8080125", year=2023,
         authors="Ghanizadeh, A. R.; Aziminejad, A.; Asteris, P. G.; et al.",
         title="Soft computing to predict earthquake-induced soil liquefaction via CPT results",
         venue="Infrastructures", cited_by_count=18,
         role_in_review="supporting — §7 hybrids & §10", pavement_domain="geotechnical (adjacent)",
         pavement_family="general", architecture="wavelet neural network",
         optimizer_hybrid="PSO", data_source="literature dataset", n_samples="109",
         interpretability_method="neighbourhood component analysis (NCA)",
         deployment_evidence="none",
         note="n=109 with 99.09% accuracy — exactly the small-n/high-skill pattern §11 examines; use as a candid methodological discussion point, not as a target."),
    dict(doi="10.3390/ai7020037", year=2026,
         authors="Safi Jahanshahi, F.; Ghanizadeh, A. R.; Naseri, H.; Mouldi, A.",
         title="Interpretable AI models based on hybrid ensemble learning methods for predicting unconfined compressive strength of cement-stabilized magnetite iron ore tailing",
         venue="AI (MDPI)", cited_by_count=1,
         role_in_review="primary — §4, §10, §12", pavement_domain="materials",
         pavement_family="general", architecture="XGBoost + 5 ensemble learners",
         optimizer_hybrid="Fennec Fox Optimization", data_source="laboratory", n_samples="",
         interpretability_method="two interpretation methods (feature importance)",
         deployment_evidence="GUI",
         note="Deployment evidence (GUI) — one of the few. Directly supports §12/PAVE-ML deployment item."),

    # --- exemplars and contrast cases from the wider field ---
    dict(doi="10.1111/mice.12263", year=2017,
         authors="Cha, Y.-J.; Choi, W.; Büyüköztürk, O.",
         title="Deep learning-based crack damage detection using convolutional neural networks",
         venue="Comput.-Aided Civ. Infrastruct. Eng.", cited_by_count=3189,
         role_in_review="landmark — §7", pavement_domain="distress-detection",
         pavement_family="general (concrete)", architecture="CNN", optimizer_hybrid="none",
         data_source="image", n_samples="", interpretability_method="none",
         deployment_evidence="none",
         note="The citation anchor of the whole vision stream; ~392 citations in 2025 alone."),
    dict(doi="10.1111/mice.70102", year=2025,
         authors="Guo, M.; Zhou, M.; Du, X.; et al.",
         title="Machine learning-based analysis of interaction effects among influencing factors on the resilient modulus of stabilized aggregate base",
         venue="Comput.-Aided Civ. Infrastruct. Eng.", cited_by_count=8,
         role_in_review="frontier exemplar — §4 & §10", pavement_domain="materials",
         pavement_family="general", architecture="gradient boosting; random forest",
         optimizer_hybrid="grid search", data_source="laboratory", n_samples="",
         interpretability_method="PDP; SHAP; bivariate interaction",
         deployment_evidence="none",
         note="Best-practice case for interaction analysis; ensemble trees beating ANNs on tabular data — a §4 theme."),
    dict(doi="10.1038/s41598-024-79588-5", year=2024,
         authors="Al Zubi, M.; Ahmad, M.; Abdullah, S.; et al.",
         title="Long short term memory networks for predicting resilient modulus of stabilized base material subject to wet-dry cycles",
         venue="Scientific Reports", cited_by_count=6,
         role_in_review="critique case — §11", pavement_domain="materials",
         pavement_family="general", architecture="LSTM", optimizer_hybrid="none",
         data_source="laboratory", n_samples="704",
         interpretability_method="SHAP", deployment_evidence="none",
         note="Architecture-task mismatch candidate: LSTM applied to non-sequential tabular records, R2=0.995/0.980. Examine for leakage and baseline strength in full text."),
    dict(doi="10.1038/s41598-022-17429-z", year=2022,
         authors="Azam, A.; Bardhan, A.; Kaloop, M. R.; et al.",
         title="Modeling resilient modulus of subgrade soils using LSSVM optimized with swarm intelligence algorithms",
         venue="Scientific Reports", cited_by_count=35,
         role_in_review="§4 & §7 hybrids", pavement_domain="materials",
         pavement_family="general", architecture="LSSVM",
         optimizer_hybrid="PSO/GWO/SOS/SSA/SMA/HHO", data_source="literature dataset",
         n_samples="891", interpretability_method="variable importance",
         deployment_evidence="none",
         note="Six-metaheuristic bake-off; the differences between winners are within noise — a §11 talking point about over-claimed hybrid gains."),
    dict(doi="10.3390/app9163221", year=2019,
         authors="Kaloop, M. R.; Kumar, D.; Samui, P.; et al.",
         title="Particle swarm optimization algorithm-extreme learning machine (PSO-ELM) model for predicting resilient modulus of stabilized aggregate bases",
         venue="Applied Sciences", cited_by_count=83,
         role_in_review="§4 & §7", pavement_domain="materials", pavement_family="general",
         architecture="ELM", optimizer_hybrid="PSO", data_source="laboratory",
         n_samples="", interpretability_method="none", deployment_evidence="none", note=""),
    dict(doi="10.1038/s41598-024-81311-3", year=2024, authors="Duan, X.",
         title="Assessment of resilient modulus of soil using hybrid extreme gradient boosting models",
         venue="Scientific Reports", cited_by_count=4,
         role_in_review="§4 & §11", pavement_domain="materials", pavement_family="general",
         architecture="XGBoost", optimizer_hybrid="black-winged kite algorithm",
         data_source="literature dataset", n_samples="", interpretability_method="",
         deployment_evidence="software",
         note="R2=0.995 against nine comparators — check baseline tuning parity in full text."),
    dict(doi="10.1016/j.ijprt.2016.11.006", year=2016,
         authors="Leiva-Villacorta, F.; Vargas-Nordcbeck, A.; Timm, D. H.",
         title="Non-destructive evaluation of sustainable pavement technologies using artificial neural networks",
         venue="Int. J. Pavement Res. Technol.", cited_by_count=34,
         role_in_review="§5", pavement_domain="structural-evaluation", pavement_family="flexible",
         architecture="ANN", optimizer_hybrid="none",
         data_source="field (NCAT Test Track)", n_samples="",
         interpretability_method="none", deployment_evidence="none",
         note="Forward-calculation under bonded vs. slip interface — a genuinely mechanistic use of ANN."),
    dict(doi="10.1139/cjce-2017-0570", year=2018,
         authors="Elbagalati, O.; Mousa, M. R.; Elseifi, M. A.; et al.",
         title="Development of a methodology to backcalculate pavement layer moduli using the traffic speed deflectometer",
         venue="Can. J. Civ. Eng.", cited_by_count=35,
         role_in_review="§5", pavement_domain="structural-evaluation", pavement_family="flexible",
         architecture="ANN", optimizer_hybrid="none", data_source="field (TSD + FWD)",
         n_samples="", interpretability_method="none", deployment_evidence="none", note=""),
    dict(doi="10.1139/cjce-2017-0132", year=2017,
         authors="Elbagalati, O.; Elseifi, M. A.; Gaspard, K.; et al.",
         title="Development of an artificial neural network model to predict subgrade resilient modulus from continuous deflection testing",
         venue="Can. J. Civ. Eng.", cited_by_count=26,
         role_in_review="§5 & §11 — positive exemplar", pavement_domain="structural-evaluation",
         pavement_family="flexible", architecture="ANN", optimizer_hybrid="none",
         data_source="field (Louisiana RWD/FWD)", n_samples="",
         interpretability_method="none", deployment_evidence="none",
         note="EXTERNAL VALIDATION: trained on Louisiana, validated on an independent Minnesota programme (R2 0.73 -> 0.72). This is the standard §11 argues the field should meet."),
    dict(doi="10.3390/su13168831", year=2021,
         authors="Baldo, N.; Miani, M.; Rondinella, F.; et al.",
         title="A machine learning approach to determine airport asphalt concrete layer moduli using heavy weight deflectometer data",
         venue="Sustainability", cited_by_count=27,
         role_in_review="§5", pavement_domain="structural-evaluation", pavement_family="airfield",
         architecture="shallow NN (Bayesian regularization)", optimizer_hybrid="none",
         data_source="field HWD + data augmentation", n_samples="",
         interpretability_method="none", deployment_evidence="none",
         note="Data augmentation on a small field set — leakage risk to assess carefully in full text."),
    dict(doi="10.1080/19942060.2018.1563829", year=2019,
         authors="Karballaeezadeh, N.; Mohammadzadeh S., D.; Shamshirband, S.; et al.",
         title="Prediction of remaining service life of pavement using an optimized support vector machine",
         venue="Eng. Appl. Comput. Fluid Mech.", cited_by_count=150,
         role_in_review="§8", pavement_domain="performance-prediction", pavement_family="flexible",
         architecture="SVR (ANN/MLP comparators)", optimizer_hybrid="particle filter",
         data_source="field (Semnan–Firuzkuh, HWD + GPR)", n_samples="147",
         interpretability_method="none", deployment_evidence="none",
         note="Iranian case study, heavily cited; n=147 with r=0.95 — small-n pattern for §11."),
    dict(doi="10.32604/cmes.2023.046025", year=2024,
         authors="Zhou, J.; Zhou, M.; Wang, Q.; et al.",
         title="Predicting the international roughness index of JPCP and CRCP rigid pavement: A random forest model hybridized with modified beetle antennae search",
         venue="CMES", cited_by_count=17, role_in_review="§8",
         pavement_domain="performance-prediction", pavement_family="rigid",
         architecture="random forest", optimizer_hybrid="modified beetle antennae search",
         data_source="LTPP", n_samples="", interpretability_method="variable importance",
         deployment_evidence="none",
         note="Claims to exceed MEPDG's IRI model — a comparison worth auditing in §11."),
    dict(doi="10.3390/ma15207303", year=2022,
         authors="Hua, W.; Yu, Q.; Xiao, Y.; et al.",
         title="Development of artificial-neural-network-based permanent deformation prediction model of unbound granular materials subjected to moving wheel loading",
         venue="Materials", cited_by_count=8, role_in_review="§4",
         pavement_domain="materials", pavement_family="general", architecture="ANN",
         optimizer_hybrid="none", data_source="laboratory (repeated load triaxial)",
         n_samples="", interpretability_method="parametric sensitivity",
         deployment_evidence="none", note=""),
    dict(doi="10.3390/ma15134386", year=2022,
         authors="Khan, K.; Jalal, F. E.; Khan, M. A.; et al.",
         title="Prediction models for evaluating resilient modulus of stabilized aggregate bases in wet and dry alternating environments: ANN and GEP approaches",
         venue="Materials", cited_by_count=21, role_in_review="§4 & §10",
         pavement_domain="materials", pavement_family="general", architecture="ANN; GEP",
         optimizer_hybrid="none", data_source="laboratory", n_samples="",
         interpretability_method="GEP equation (intrinsic); sensitivity",
         deployment_evidence="equation",
         note="Same dataset family as Al Zubi 2024 and Guo 2025 — a near-duplicate-substrate cluster worth naming explicitly in §8/§11."),
    dict(doi="10.1016/j.conbuildmat.2018.08.011", year=2018,
         authors="Dorafshan, S.; Thomas, R. J.; Maguire, M.",
         title="Comparison of deep convolutional neural networks and edge detectors for image-based crack detection in concrete",
         venue="Constr. Build. Mater.", cited_by_count=755, role_in_review="§7 — baseline honesty",
         pavement_domain="distress-detection", pavement_family="general (concrete)",
         architecture="CNN vs. classical edge detectors", optimizer_hybrid="none",
         data_source="image", n_samples="", interpretability_method="none",
         deployment_evidence="none",
         note="One of the few papers that benchmarks DL against a genuinely tuned classical baseline. Model case for the §11 baseline-strength criterion."),
    dict(doi="10.1186/s40537-023-00727-2", year=2023,
         authors="Alzubaidi, L.; Bai, J.; Al-Sabaawi, A.; et al.",
         title="A survey on deep learning tools dealing with data scarcity: definitions, challenges, solutions, tips, and applications",
         venue="J. Big Data", cited_by_count=832, role_in_review="§13 — methods import",
         pavement_domain="cross-domain", pavement_family="n/a",
         architecture="TL/SSL/GAN/PINN survey", optimizer_hybrid="", data_source="literature",
         n_samples="", interpretability_method="", deployment_evidence="",
         note="Source for the data-scarcity remedies we recommend importing into pavement work."),
    dict(doi="10.1016/j.autcon.2022.104440", year=2022,
         authors="Baduge, S. K.; Thilakarathna, S.; Perera, J. S.; et al.",
         title="Artificial intelligence and smart vision for building and construction 4.0: Machine and deep learning methods and applications",
         venue="Autom. Constr.", cited_by_count=948, role_in_review="§1 framing",
         pavement_domain="cross-domain", pavement_family="n/a", architecture="survey",
         optimizer_hybrid="", data_source="literature", n_samples="",
         interpretability_method="", deployment_evidence="",
         note="Shows the style and depth Automation in Construction rewards in a review."),
]


def main() -> None:
    out = Path(__file__).with_name("seed_bibliography.csv")
    with out.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        for r in R:
            w.writerow({c: r.get(c, "") for c in COLUMNS})
    print(f"wrote {len(R)} verified records -> {out}")


if __name__ == "__main__":
    main()
